apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-pod
spec:
  replicas: 2  # Adjust replicas to 2 to ensure no more than two instances per node
  selector:
    matchLabels:
      app: weather-pod
  template:
    metadata:
      labels:
        app: weather-pod
    spec:
      containers:
      - name: weather-pod
        image: nishant2081/k123s:latest
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-api-secret
              key: api-key
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: weather-api-config
              key: weatherUrl
        - name: Forecast_URL
          valueFrom:
            configMapKeyRef:
              name: weather-api-config
              key: forecastUrl
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: weather-api-config
              key: HOST
        ports:
        - containerPort: 7878
      tolerations:
      - key: "weather-app"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule" # This prevents other pods from being scheduled on the nodes with this taint
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master  # Assuming master nodes are not being used
                operator: DoesNotExist  # This ensures that nodes with this label are not considered
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - weather-pod
            topologyKey: "kubernetes.io/hostname" # This ensures that pods are not scheduled on nodes already containing a weather-pod
