apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-pod
  template:
    metadata:
      labels:
        app: weather-pod
    spec:
      containers:
      - name: weather-pod
        image: nishant2081/k123s:latest
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-api-secret
              key: api-key
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: weather-api-config
              key: weatherUrl
        ports:
        - containerPort: 7878
