apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-pod
  namespace: default
spec:
  releaseName: weather-pod
  chart:
    repository: demoproject
    name: weatherapp
    version: 0.1.0
  values:
    replicaCount: 2
    image:
      repository: nishant2081/k123s
      pullPolicy: IfNotPresent
      tag: "latest"
    service:
      type: NodePort
      port: 80
    ingress:
      enabled: false
    env:
      API_KEY:
        secretName: weather-api-secret
        secretKey: api-key
      API_URL: weather-api-config
      Forecast_URL: weather-api-config
      HOST: weather-api-config
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    tolerations:
      - key: "weather-app"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: DoesNotExist
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - weather-pod
            topologyKey: "kubernetes.io/hostname"
  interval: 5m
  # Release to be rolled out automatically
  automated: 
    prune: true
    selfHeal: true
