{{- if .Values.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weather-pod.fullname" . }}
  labels:
    app: {{ include "weather-pod.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "weather-pod.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "weather-pod.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
{{ toYaml .Values.env | indent 12 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
