apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: kamal
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
