name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: imnishantdevops/demoproject  # Specify the repository owned by imnishantdevops
        path: weatherapp   # Specify the directory path within the repository

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Navigate to project directory
      run: cd weatherapp

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        # Your deployment steps here, e.g., deploying to a hosting service like Heroku or AWS
        echo "Deploying the application..."
