name: Pull Request Example

on:
  pull_request:
    branches:
      - main
    paths:
      - 'demoproject/weatherapp/**'  # Trigger only when changes occur within the weatherapp directory
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: demoproject/weatherapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'npm'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test
